---
- name: configure SOE
  hosts: serverb
  tasks:
    - name: configure /etc/hosts
      ansible.builtin.template:
        src: host.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

