---
- name: configure SOE
  hosts: serverb
  vars:
    - system_owner: serverb.example.com
  tasks:
    - name: configure /etc/motd
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'


