---
- name: create  a user through the ansible vault method
  hosts: serverb
  vars_files:
    - secret.yaml
  tasks:
    - name: add the user sam
      ansible.builtin.user:
        name: "{{user_name}}"
        state: present
        password: "{{pwhash | password_hash('sha512')}}"
